### ISSUE TITLE
Zeus Black Screen on rejoin / death.

### ISSUE THREAD

**Issue by Kissingya** [56curious/VKN_Official_Mod#15]
**Describe the bug**
Upon leaving the Zeus slot for any reason: disconnecting / crashing / Dying. Coming back to any slot turns into a black screen, you can hear the sound of a body falling. Zeus modules duplicated (to 8 known). When pressing Y you could heard the Zeus "Ping". Funnily enough if someone Pinged Zeus you'd hear it aswell.

**To Reproduce**
Steps to reproduce the behaviour:
1. Load a Mission on the server.
2. Die / Rejoin Server.
3. Black Screen with "dead" Zeus modules duplicating.

**Expected behaviour**
Having Zeus Interface opens when joining.
**Screenshots**
None. It would be just a black screen.

**Desktop (please complete the following information):**
Windows.

**Additional context**
None.

**Comment by 56curious** [comment]
```
{
	if (!isnull (getassignedcuratorunit _x)) then {
		_unit = getassignedcuratorunit _x;
		if (isnull (getassignedcuratorlogic _unit)) then {
			unassignCurator _x;
			sleep 1;
			_unit assignCurator _x;
			if (isClass (configFile >> "CfgPatches" >> "task_force_radio")) then {
				_unit call TFAR_fnc_isForcedCurator;
			};
		};
	};
} foreach allcurators;
```
Need to test but a possible fix via https://forums.bohemia.net/forums/topic/190599-zeus-black-screen-bug-no-interface-after-reconnect/

**Comment by 56curious** [comment]
Fixed in next update.
