### ISSUE TITLE
RHS Lasers and Bipods not compatable with AK5C

### ISSUE THREAD

**Issue by VKN-Goblin** [56curious/VKN_Official_Mod#18]
**Describe the bug**
Any non-vanilla lasers/flashlights are not able to be mounted on the AK5C, also No Bipod/Grip options are available

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Rifles in arsenal, AK5C'
2. Click on 'Lasers/Bipods'
3. Scroll down to 'any non-vanilla optics'
4. none available

**Expected behaviour**
Other MOd optics/Bipods should be able to be used.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser Chrome

**Additional context**

**Comment by 56curious** [comment]
Fix the issue with the template and not just the template 😄

**Comment by 56curious** [comment]
Fixed side rails and magazines, bipods are still not inheriting correctly. RHS grips require P3D edits on the source file, however this is too much work for the mean time. Will make a note and get round to fixing underbarrel and grip options.
