### ISSUE TITLE
zeus error

### ISSUE THREAD

**Issue by JBryanVKN** [56curious/VKN_Official_Mod#19]
**Describe the bug**
zeus slots are not working in the mission

**To Reproduce**
Steps to reproduce the behaviour:
1. Use template tool
2. upload the mission to the server
3. try to log in as a zeus

**Expected behaviour**
zeus should work

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser yandex

**Additional context**

**Comment by 56curious** [comment]
Issue found that item was not setup to sync. Will be fixed in the next commit and Hot fix #4.

**Comment by 56curious** [comment]
Fixed.
