### ISSUE TITLE
Fire rate changing on custom weapons

### ISSUE THREAD

**Issue by Djennxs** [56curious/VKN_Official_Mod#2]
**Describe the bug**
When I, for example, use the AK5C it will always change the fire rate back to full auto when switching between items.

**To Reproduce**
Steps to reproduce the behaviour:
1. Pick the AK5C
2. Change the fire rate to semi-automatic
3. Switch to another item, for example your binoculars or secondary
4. Switch back to the AK5C

**Expected behaviour**
The fire rate should remain on semi-automatic after changing back to the AK5C.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Latest version of ArmA 3 and the Viking PMC mod

**Additional context**
This is not a game breaking bug, more a "please fix in the future"-problem.

**Comment by 56curious** [comment]
All weapons seem to reset upon investigation.
