### ISSUE TITLE
Mission Template Tool Notification Bug

### ISSUE THREAD

**Issue by skywalker1162** [56curious/VKN_Official_Mod#20]
**Describe the bug**
Error message in attached screenshot pops up when you confirm the notification
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Editor'
2. Click on 'New Terrain and enter confirmed on the pop up'
3. See error

**Expected behaviour**
Error message in attached screenshot pops up when you confirm the notification

**Screenshots**
Added
![20210110150635_1](https://user-images.githubusercontent.com/15173388/104119644-c6a61c80-5356-11eb-96e8-9226e928a483.jpg)

**Comment by 56curious** [comment]
Thanks, will be included in hotfix #3.

**Comment by 56curious** [comment]
Fixed.
