### ISSUE TITLE
RHS & NI Arms Magazines not compatable with AK5C

### ISSUE THREAD

**Issue by VKN-Goblin** [56curious/VKN_Official_Mod#23]
**Describe the bug**
Only AK5 Mags will work with the weapons not compat. with RHS or NI Arms

**To Reproduce**
Steps to reproduce the behaviour:
Go to 'set current rifle in arsenal as AK5C'
Click on 'Magazines'
Scroll down to 'any non-vanilla magazines'
none available

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by 56curious** [comment]
Will add to the list, thanks for reporting

**Comment by 56curious** [comment]
magazines added.
