### ISSUE TITLE
Arsenal

### ISSUE THREAD

**Issue by Tom07904** [56curious/VKN_Official_Mod#24]
**Describe the bug**
Arsenal Init doesn't work

**To Reproduce**
Steps to reproduce the behaviour:
1. use the Mission template tool
2. click ok on the ammo box
3. init file expected nothing

**Expected behaviour**
Arsenal to work on the ammobox at spawn

**Comment by 56curious** [comment]
Fix was found and added. String was lowercase and function expected different.
