### ISSUE TITLE
Baguette Launcher

### ISSUE THREAD

**Issue by Bspade** [56curious/VKN_Official_Mod#36]
Hi Curious,

Could you please take some time to make a rocket launcher skin in Baguette shape ?
Many Arma French guys will love to go to combat with a baguette on their back ;)

It can be a bit meme but i'm sure that you will fine people to dl that on the workshop.
![image](https://user-images.githubusercontent.com/89389232/130433931-1797b73d-a9ee-4f50-92f3-453dd8baa8c8.png)

**Comment by Shagger-dev** [comment]
Not happening for obvious reasons.
