### ISSUE TITLE
Custom Faction Present in Eden missing in Zeus.

### ISSUE THREAD

**Issue by Kissingya** [56curious/VKN_Official_Mod#39]
**Describe the bug**
Three custom factions not showing up in Zeus but showing in Eden list. Using only Vikingmodset.
Factions being:
Blufor: Taiga - Legion
Opfor: Modern China

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Eden Editor
2. Click on Start Mission
3. Scroll down to Faction lists
4. See missing factions.

**Expected behaviour**
Have said factions shown up in Zeus Interface.

**Screenshots**
Sent in Techsupport of Viking main Discord, 11:04 AM Paris time.
![20210907104832_1](https://user-images.githubusercontent.com/66916958/132321992-107c8e84-3416-4153-b3d8-9621e07bfde2.jpg)
![20210907104749_1](https://user-images.githubusercontent.com/66916958/132322000-6e8bd35f-b90d-4c68-97b3-ed333ed175f7.jpg)
![20210907104827_1](https://user-images.githubusercontent.com/66916958/132322012-540a3f03-f11f-4095-ab38-7616485dab88.jpg)
![20210907104747_1](https://user-images.githubusercontent.com/66916958/132322018-e9e93363-0c0d-41fd-96d5-b2b996a57bcc.jpg)

**Additional context**
Wonderful job you lads did and are still doing :)

**Comment by 56curious** [comment]
Issue is fixed.
