### ISSUE TITLE
GTA like screenshots for loading menu

### ISSUE THREAD

**Issue by MaxKupleoni** [56curious/VKN_Official_Mod#55]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
This https://www.reddit.com/r/arma/comments/r0rzo2/awhile_ago_i_made_gta_inspired_screenshots_of/

**Describe alternatives you've considered**
Do them yourself? :/

**Additional context**
/

**Comment by 56curious** [comment]
In startup loading screens. Will be in enxt update,
