### ISSUE TITLE
Finished Custom Faction: North America 2020.

### ISSUE THREAD

**Issue by Kissingya** [56curious/VKN_Official_Mod#6]
Modification of RHS US Army with intermediate protection. Using Base game CTRG as a Faction Base. Couldn't find intermediate UCP Pattern vests though so using MTP Crye Lite Carrier instead (Viking asset)
[North America 2020.txt](https://github.com/56curious/VKN_Official_Mod/files/5035497/North.America.2020.txt)

**Comment by Shagger-dev** [comment]
Could you please follow the template in order to help us Identify the actual problem here.
****Describe the bug**
**To Reproduce****

**Desktop (please complete the following information):**
**OS:**
**Version:** 
**Additional context**
